---
- hosts : all
  become: true
  tasks:
          - name: update OS
            yum:
              name: '*'
              state: latest
            register: updated
          
          - name: enable python '3' repo
            command : amazon-linux-extras enable python3.8

          - name: install git epel python
            yum:
                    name:
                            - git
                            - amazon-linux-extras
                            - python3.8
                    state: latest

          - name: reboot servers after update
            reboot: 
              reboot_timeout: 3600
            when: updated.changed
      

