---
- name: install flask cluster
  hosts: all
  become: true 
  tasks:
      - name: update OS
        yum:
          name: '*'
          state: latest
      - name: enable python '3' repo
        command : amazon-linux-extras enable python3.8
      - name: install git epel python docker
        yum:
          name:
            - git
            - amazon-linux-extras
            - python3.8
            - docker
            - python-pip 
          state: latest
      - name: install python docker moudle
        shell: pip install docker --user 

- hosts: ansible
  become: true
  tasks:
      - name: Create folder for Git repo
        ansible.builtin.file:
            path: /home/ec2-user/web-p
            state: directory
            mode: '0755'      
      - name: git init the folder
        shell: git init
        args:
          chdir: /home/ec2-user/web-p
      - name: Get stuff from git - ansible
        shell: git pull https://github.com/TalHason/rhassignment.git 
        args:
          chdir: /home/ec2-user/web-p        
      - name: build container image
        docker_image:
          name: flask-server:latest
          build: 
            path: /home/ec2-user/web-p/Docker
          source: build
      - name: Docker Login
        docker_login:
          username: talhason
          password: 9e38122f-247b-4d59-8e80-fc0babc354d9   
          email: talhason3105@gmail.com
      - name: push image to docker hub repo
        community.docker.docker_image:
          name: flask-server:latest
          repository: talhason/rhassignment:flaskserver
          push: yes
          source: local

- hosts: web
  become: true
  tasks:
      - name: start docker service demon
        ansible.builtin.service:
          name: docker
          state: started
      - name: Docker Login
        docker_login:
          username: talhason
          password: 9e38122f-247b-4d59-8e80-fc0babc354d9
          email: talhason3105@gmail.com   
      - name: start the flask server docker image
        docker_container:
          image: flask-server:latest 
          name: flask-server
          state: started
          auto_remove: true
          ports:
            - "5000:5000"

- hosts: haproxy
  become: true
  tasks:
      - name: install HAproxy
        yum:
         name: haproxy
         state: latest
         #      - name: get haproxy conf file from git
         #          get_url:
         #            url: https://github.com/TalHason/rhassignment/blob/main/haproxy/haproxy.cfg
         #            dest: /home/ec2-uesr/haproxy.cfg
         #            mode: 0777
      - name: Get Conf File from repo
        shell: wget https://github.com/TalHason/rhassignment/blob/main/haproxy/haproxy.cfg
        args:
          chdir: /home/ec2-user/

      - name: copy new haproxy conf to server etc folder
        copy:
          src: /home/ec2-uesr/haproxy.cfg
          dest: /etc/haproxy/
          force: yes
      - name: start the haProxy Deamon
        service:
          name: haproxy
          state: started





