---
#install env programs
- hosts : all
  become: true
  tasks:
          - name: update OS
            yum:
              name: '*'
              state: latest
            register: updated

          - name: enable python '3' repo
            command : amazon-linux-extras enable python3.8

          - name: install git epel python docker
            yum:
              name:
                - git
                - amazon-linux-extras
                - python3.8
                - docker  
              state: latest

          - name: reboot servers after update
            reboot:
              reboot_timeout: 3600
            when: updated.changed

- hosts: ansible
  become: true
  tasks:
      - name: Create folder for Git repo
        ansible.builtin.file:
            path: /home/ec2-user/web-p
            state: directory
            mode: '0755'      
      - name: Get stuff from git
        shell: git pull 'git@github.com:TalHason/rhassignment.git main'
        args:
          chdir: /home/ec2-user/web-p
           
             
      - name: build container image
        community.docker.docker_image:
        name: flask-server:latest
        build: 
          path: /home/ec2-user/web-p/Docker
          source: build
      - name: Docker Login
        docker_login:
          registry: https://hub.docker.com/repository/docker/talhason/rhassignment
          username: talhason
          debug: true
          password: "@3-Z6.dW~vcmt2#"   
      - name: push image to docker hub repo
        community.docker.docker_image:
          name: flask-server:latest
          repository: talhason/rhassignment:flaskserver
          push: yes
          source: local

- hosts: web
  become: true
  tasks:
      - name: start docker service demon
        ansible.builtin.service:
          name: docker
          state: started
      - name: Docker Login
        docker_login:
          registry: https://hub.docker.com/repository/docker/talhason/rhassignment
          username: talhason
          debug: true
          password: "@3-Z6.dW~vcmt2#"    
      - name: start the flask server docker image
        docker_container:
          image: flask-server:latest 
          name: nginx
          state: started
          auto_remove: true
          ports:
            - "5000:5000"
- hosts: haproxy
  become: true
  tasks:
      - name: install HAproxy
        yum:
         name: haproxy
         state: latest
      - name: get haproxy conf file from git
          get_url:
            url: https://github.com/TalHason/rhassignment/blob/main/haproxy/haproxy.cfg
            dest: /tmp/
            mode: '0640'
      - name: copy new haproxy conf to server etc folder
        ansible.builtin.copy:
          src: /tmp/haproxy.cfg
          dest: /etc/haproxy/
          force: yes
      - name: start the haProxy Deamon
        ansible.builtin.service:
          name: haproxy
          state: started





